spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888



#spring.application.name=service-registry
#server.port=8761
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

   